title: Your awesome title
lang: en
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /post/:year/:month/:day/:title.html

plugins:
  - jekyll-paginate-v2
  - jekyll-feed

pagination:
  enabled: true
  debug: false
  per_page: 1
  permalink: /:num/
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  categories:
    layouts:
      - 'filter.html'
    title: 'Category: :cat'
    permalink: '/category/:cat'
  collections:
    layouts:
      - 'filter.html'
    title: 'Collection: :coll'
    permalink: '/collections/:coll'
  tags:
    layouts:
      - 'filter.html'
    title: 'Tag: :tag'
    permalink: '/tag/:tag'
